"""Generate the two native stage definitions from their editable geometry."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
stages = [json.loads((ROOT / 'tools' / name).read_text()) for name in ('level.json', 'grove.json')]
output = ['/* Generated by tools/make_level_data.py. */', '#define BALL_COUNT 6', '#define GOON_COUNT 3',
          f'#define MAX_LEVEL_SOLIDS {max(len(s["solids"]) for s in stages)}',
          f'#define MAX_LEVEL_GAPS {max(len(s["gaps"]) for s in stages)}', '''typedef struct {
    INT16 width;
    UBYTE solid_count, gap_count, first_gate, last_gate, entry_door;
    const INT16 (*solid_data)[4];
    const INT16 (*gap_data)[3];
    const INT16 (*ball_data)[2];
    const INT16 (*goon_data)[2];
    INT16 bell_x[2], bell_y[2], camera_entry[2], camera_center[2];
} KittieLevel;''']
rows = lambda data, scale: ','.join('{' + ','.join(str(v * scale) for v in row) + '}' for row in data)
configs = []
for n, stage in enumerate(stages):
    assert len(stage['balls']) == 6 and len(stage['goons']) == 3
    assert stage['solids'] == sorted(stage['solids'])
    assert [s[2] for s in stage['solids']] == sorted(s[2] for s in stage['solids']), 'Collision cache requires monotone right edges'
    assert 0 < stage['width'] <= 2000
    for field, width in [('solids',4),('gaps',3),('balls',2),('goons',2)]:
        output.append(f'static const INT16 stage{n}_{field}[{len(stage[field])}][{width}]={{{rows(stage[field],16)}}};')
    centers = stage.get('camera_centers', [392,1112])
    entries = stage.get('camera_entries', [328,1052])
    arrays = [[c['bell_x'] * 16 for c in stage['courts']], [c['bell_y'] * 16 for c in stage['courts']], [v * 16 for v in entries], centers]
    fields = [str(stage['width']), str(len(stage['solids'])), str(len(stage['gaps'])), *map(str,stage['gate_indices']), str(stage['door_index']), *[f'stage{n}_{field}' for field in ('solids','gaps','balls','goons')]]
    configs.append('{' + ','.join(fields) + ',' + rows(arrays,1) + '}')
output.append('static const KittieLevel levels[2]={' + ',\n'.join(configs) + '};')
(ROOT / 'plugins/kittie/engine/include/states/kittie_levels.h').write_text('\n'.join(output) + '\n')
print('Generated courtyard and 11-screen grove geometry.')
