"""Small anchored native tile families: leaf tips and banquet bunting."""
from pathlib import Path
import json
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve().parents[1]
C=['#e0f8cf','#86c06c','#306850','#071821']
rgb=[tuple(bytes.fromhex(c[1:])) for c in C]
def bits(im):
    out=[]
    for y in range(8):
        row=[rgb.index(im.getpixel((x,y))) for x in range(8)]
        out.extend([sum(((v>>b)&1)<<(7-x) for x,v in enumerate(row)) for b in (0,1)])
    return out
families=[]
leaves=[]
for phase in (0,1,0,-1):
    tile=Image.new('RGB',(8,8),C[0]);d=ImageDraw.Draw(tile)
    d.line((0,5,5,4),fill=C[2]);d.line((0,4,3,3),fill=C[1],width=2)
    d.line((3,3+phase,6,2+phase),fill=C[1],width=2)
    d.point((5,4),fill=C[1]);leaves.append(tile)
im=Image.open(ROOT/'assets/backgrounds/olive_grove.png').convert('RGB')
for x,y in [(72,64),(504,64),(1400,64)]:im.paste(leaves[0],(x,y))
im.save(ROOT/'assets/backgrounds/olive_grove.png');families.append([bits(t) for t in leaves])
bunting=[]
for phase in (0,1,0,-1):
    tile=Image.new('RGB',(16,8),C[0]);d=ImageDraw.Draw(tile)
    d.line((0,0,15,0),fill=C[2]);d.polygon([(0,1),(12,1),(6+phase,7)],fill=C[1]);d.point((6+phase,5),fill=C[2]);bunting.append(tile)
im=Image.open(ROOT/'assets/backgrounds/banquet.png').convert('RGB');d=ImageDraw.Draw(im)
for left,right in ((8,136),(336,800),(872,1024)):
    for x in range(left+8,right-12,24):
        d.rectangle((x,25,x+15,32),fill=C[0]);im.paste(bunting[0],(x,24))
im.save(ROOT/'assets/backgrounds/banquet.png')
for x in (0,8):families.append([bits(t.crop((x,0,x+8,8))) for t in bunting])
rows=lambda x:'{'+','.join(map(str,x))+'}'
text='/* Generated by tools/make_world_motion.py: leaves, then two bunting tiles. */\nstatic const UBYTE world_motion[3][4][16]={'+','.join('{'+','.join(rows(p) for p in f)+'}' for f in families)+'};\n'
(ROOT/'plugins/kittie/engine/include/states/kittie_world_motion.h').write_text(text)
print('Three animated tile families, four held phases; fixed anchors and landing edges.')
