"""Four native ripple phases for the courtyard's two exclusive water tiles.

The banks, top boundary, tile palette and collision are fixed. Only the short
interior strokes move one pixel per phase, with the lower stroke offset.
"""
from pathlib import Path
from PIL import Image
import json
ROOT = Path(__file__).resolve().parents[1]
level=json.loads((ROOT/'tools/level.json').read_text())
im=Image.open(ROOT/'assets/backgrounds/courtyard.png').convert('RGB')
colors=[(224,248,207),(134,192,108),(48,104,80),(7,24,33)]
phases=[]
for row, y in enumerate((128,136)):
    original=im.crop((level['gaps'][0][0],y,level['gaps'][0][0]+8,y+8))
    # Changing a shared VRAM tile is safe only when every use is water.
    for yy in range(0,144,8):
        for xx in range(0,level['width'],8):
            if im.crop((xx,yy,xx+8,yy+8)).tobytes()==original.tobytes():
                assert yy==y and any(a<=xx<b for a,b,_ in level['gaps'])
    row_phases=[]
    for phase in range(4):
        frame=original.copy()
        shift=(0,1,2,1)[(phase+row)%4]
        streak_y=4 if row==0 else 3
        # Circular shift gives a continuous repeated channel surface.
        for x in range(8):
            frame.putpixel((x,streak_y),original.getpixel(((x-shift)%8,streak_y)))
        data=[]
        for yy in range(8):
            lo=hi=0
            for x in range(8):
                index=colors.index(frame.getpixel((x,yy)))
                lo|=(index&1)<<(7-x);hi|=(index>>1)<<(7-x)
            data.extend((lo,hi))
        row_phases.append(data)
    phases.append(row_phases)
body=',\n'.join('{'+','.join('{'+','.join(str(v) for v in data)+'}' for data in row)+'}' for row in phases)
(ROOT/'plugins/kittie/engine/include/states/kittie_water.h').write_text('/* Generated by tools/make_water_motion.py. Exclusive courtyard water only. */\nstatic const UBYTE courtyard_water[2][4][16]={\n'+body+'\n};\n')
print('Generated two exclusive water tiles, four phases; banks and top edge fixed.')
