"""Generate the user-facing HTML guide and maps from authoritative stage JSON."""
from pathlib import Path
import json, html, hashlib
ROOT=Path(__file__).resolve().parents[2]
GAME=ROOT/'courtyard'; DESIGN=ROOT/'design'
style='''body{margin:0;background:#f5edd8;color:#403b3d;font:16px/1.65 system-ui,sans-serif}main{max-width:1060px;margin:auto;padding:40px 24px 64px}h1{font-size:42px;line-height:1.12;max-width:800px}h2{font-size:24px;line-height:1.25;margin-top:32px}h3{font-size:18px}a{color:#704373}p{max-width:800px}.lead{font-size:21px}.note{padding:18px 22px;background:#e5e8d2;border-left:4px solid #66834f}img{max-width:100%;height:auto;image-rendering:pixelated}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{padding:18px;background:#faf5e9;border:1px solid #cbb78f}.card p{font-size:15px}.map{overflow:auto;border:1px solid #cbb78f;background:#faf5e9}table{border-collapse:collapse;width:100%;font-size:15px}th,td{text-align:left;vertical-align:top;border-bottom:1px solid #cbb78f;padding:12px 8px}code{font-size:12px;overflow-wrap:anywhere}.small{font-size:13px;color:#675e57}@media(max-width:700px){.cards{grid-template-columns:1fr}h1{font-size:32px}}'''
def doc(title,body):return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>{style}</style></head><body><main>{body}</main></body></html>'
def diagram(level):
 w=level['width'];parts=[f'<svg width="{w}" height="176" viewBox="0 0 {w} 176" role="img" aria-label="Stage geometry, wool, bells and patrols"><rect width="{w}" height="176" fill="#faf5e9"/><rect y="128" width="{w}" height="16" fill="#66834f"/>']
 for x in range(0,w,160):parts.append(f'<path d="M{x},20V144" stroke="#cbb78f" stroke-dasharray="4 4"/><text x="{x+8}" y="15" font-size="12">{x//160+1}</text>')
 for x,r,_ in level['gaps']:parts.append(f'<rect x="{x}" y="128" width="{r-x}" height="16" fill="#83c7dc"/>')
 for i,(x,y,r,b) in enumerate(level['solids']):
  if i in level['gate_indices'] and level.get('initial_gate',0)&(1<<level['gate_indices'].index(i)):continue
  color='#9773b3' if i in level['gate_indices'] else '#a18969'
  opacity='.4' if i==level['door_index'] else '1'
  parts.append(f'<rect x="{x}" y="{max(y,20)}" width="{r-x}" height="{b-max(y,20)}" fill="{color}" opacity="{opacity}"/>')
 for i,(lo,hi) in enumerate(level['goons']):
  y=level.get('goon_heights',[128]*3)[i]-8
  parts.append(f'<path d="M{lo},{y}H{hi}" stroke="#704373"/><circle cx="{(lo+hi)/2}" cy="{y}" r="6" fill="#704373"/>')
 for x,y in level['balls']:parts.append(f'<circle cx="{x}" cy="{y}" r="5" fill="#d87098" stroke="#733b65"/>')
 for i,c in enumerate(level['courts']):
  if level.get('initial_gate',0)&(1<<i):continue
  x,y=c['bell_x'],c['bell_y'];parts.append(f'<path d="M{x-5},{y+4}h10l-2,-9h-6z" fill="#d7a343"/>')
 parts.append('</svg>');return ''.join(parts)
levels=[json.loads((GAME/f'tools/{n}.json').read_text()) for n in ('level','grove','banquet')]
names=['The courtyard','The olive grove','The wedding banquet']
files=['level-plan.html','olive-grove.html','banquet.html']
intros=[
 'Eight screens of safe planters, the first high bell, a short route fork and a low table shot. It teaches collection, throwing, recovery and the cost of falling.',
 'Eleven screens built around broad raised stone islands and irrigation channels. There is no opening bell court. An optional high path carries wool above a lower patrol lane, followed by one enclosed bell garden.',
 'Nine screens inside the wedding hall. A low opening shot leads to long table crossings, chair steps and a final cake-table bell. The wedding arch leads to the photo ending.'
]
for name,file,level,intro in zip(names,files,levels,intros):
 sections=level.get('sections',[])
 table='<table><tr><th>Screens</th><th>Section</th><th>Play</th></tr>'+''.join(f'<tr><td>{html.escape(s["screens"])}</td><td>{html.escape(s["name"])}</td><td>{html.escape(s["action"])}</td></tr>' for s in sections)+'</table>' if sections else ''
 body=f'<h1>{name}</h1><p class="lead">{intro}</p><p><a href="version-1.html">Version 1 guide</a> · <a href="../courtyard/build/kittie-complete-v1.gbc">Playable ROM</a></p><div class="map">{diagram(level)}</div><p class="small">Scroll to inspect the full stage. Pink circles are wool; plum circles and lines are constant-speed patrols; blue strips are fatal water; gold marks are bells. Purple bars are bell gates. The pale tall bar is the closing court shutter. Vertical guides mark 160-pixel screens.</p>{table}<h2>Rules that carry across stages</h2><p>Collect up to three balls. B throws low; Up+B lobs. Balls defeat goons and ring bells. There is no automatic return, recall or jump boost. Goon contact costs a heart. Water or losing every heart resets the current stage. Start retries; Select returns to the stage menu. Clearing a stage saves the next unlock.</p><p>Native playtests reached the ending. The grove’s upper and lower routes passed separately. Its upper ledge ends early enough to leave the lower water-jump takeoff clear. Both grove and banquet final courts were completed after entering empty.</p>'
 (DESIGN/file).write_text(doc(name,body))
native=hashlib.sha256((GAME/'build/kittie-complete-v1.gbc').read_bytes()).hexdigest()
web=hashlib.sha256((GAME/'build/feedback-web/rom/kittie-has-other-plans.gbc').read_bytes()).hexdigest()
cards=''.join(f'<article class="card"><h3>{n}</h3><p>{i}</p><a href="{f}">View map</a></article>' for n,i,f in zip(names,intros,files))
body=f'''<p class="small">Version 1 · 2 October 2026 · Game Boy Color / ModRetro Chromatic</p><h1>Kittie, a pocketful of wool, and a Tuscan wedding.</h1>
<p class="lead">A complete three-stage version with 28 screens, saved stage unlocks, original music and a wedding ending.</p>
<p><a href="../courtyard/build/kittie-complete-v1.gbc">Download version 1 ROM</a> · <a href="../courtyard/project.gbsproj">Editable project</a> · <a href="expansion-roadmap.html">Development status</a></p>
<div class="cards">{cards}</div>
<p><a href="cover-review.html">Native cover and paw animation review</a></p><h2>Kittie follows the original photographs</h2><img src="../courtyard/artifacts/kittie-face-comparison.png" width="400" height="190" alt="Before and version 1 native sprite comparison, with a clearer oval face and separated eyes and smile">
<p>The original front and side photographs remain the reference for every sprite revision. His face keeps the low oval, crown marking, closed eyes, pale nose and broad stitched grin. His low body and short legs stay. His front paw now matches the torso taupe, with one-pixel body and paw contours. The face pixels remain fixed in all 16 poses; reactions use his body and paws. One pink ball rides on his back; the beige shape under his face is his paw. He still cuddles wool while idle.</p>
<p><a href="../courtyard/source-art/character-reference/reference-current-front.png">Original front photo</a> · <a href="../courtyard/source-art/character-reference/reference-current-side.png">Original side photo</a></p><h2>The native cover opens the game</h2><img src="../courtyard/artifacts/version-1-title.png" width="320" height="288" alt="Actual native cover screen showing Kittie with his paws on the ledge"><p>Cover version 10 uses broad curved shading, a fuller chin, naturally asymmetric whiskers and a warm stone ledge. Press A or Start to show the stage selector over the artwork; B closes it. Sky colors cannot map onto the fur. Seven tile palettes preserve a separate UI palette. Both paws remain on the ledge. The wedding ending uses the exact gameplay sprite.</p><h2>Native gameplay</h2><img src="../courtyard/artifacts/version-1-native-3.png" width="320" height="288" alt="Final sprite in actual courtyard gameplay"><img src="../courtyard/artifacts/version-1-native-73.png" width="320" height="288" alt="Actual olive grove gameplay">
<p>These are genuine emulator frames from the final release. The <a href="../courtyard/artifacts/complete-v1-playthrough.gif">earlier gameplay montage</a> records both grove routes and the finale before the final face and menu revision. The grove climbs across stone islands; the banquet hops across tables. Patrols no longer pause or charge. Living goons move at 0.75 pixels per game update, turning at their authored endpoints.</p>
<h2>Controls and saved progress</h2>
<table><tr><th>Action</th><th>Browser</th><th>Chromatic</th></tr><tr><td>Move and collect wool</td><td>Arrows; touch a ball</td><td>D-pad; touch a ball</td></tr><tr><td>Jump; hold for height</td><td>Z</td><td>A</td></tr><tr><td>Low throw / high lob</td><td>X / Up + X</td><td>B / Up + B</td></tr><tr><td>Retry current stage</td><td>Enter</td><td>Start</td></tr><tr><td>Return to cover</td><td>P</td><td>Select</td></tr><tr><td>Open / close title selector</td><td>Z or Enter / X</td><td>A or Start / B</td></tr><tr><td>Choose a stage or continue dialogue</td><td>Arrows, Z</td><td>D-pad, A</td></tr></table>
<p>Clearing the courtyard unlocks the grove; clearing the grove unlocks the banquet. Unlocks are saved to cartridge RAM. The title menu reads them when the game starts. Replaying an earlier stage does not remove later unlocks. There are no mid-stage checkpoints. Each stage starts with three hearts and its own six-ball supply.</p>
<p>Goon contact costs one heart and gives knockback plus brief protection. Losing every heart or falling into water resets the whole current stage. Wool stays where it lands until recovered; a ball lost in water stays lost until retry. Both mandatory closing courts keep a local ball available.</p>
<h2>Clearer feedback while playing</h2><p>A successful hit shakes the bell and raises its gate. The bell turns green and the raised gate keeps a green check, so the open state remains visible. The camera holds the court during the short reaction. The low tables have a shaded wool passage beneath an opaque apron. B sends wool underneath; A takes Kittie over. Hearts and wool slots now sit on dark backings, with visible outlines when empty.</p><img src="../courtyard/artifacts/feedback-open-gate.png" width="320" height="288" alt="Green rung bell and raised gate with an open marker"><img src="../courtyard/artifacts/feedback-low-table.png" width="320" height="288" alt="Wool travels beneath the low table apron"><img src="../courtyard/artifacts/feedback-damage.png" width="320" height="288" alt="Two filled hearts and a clearly outlined empty heart after contact">
<h2>Music and texture</h2><p>Each stage has its own original melody and soft bass accompaniment. Courtyard and banquet themes use C major; the grove uses A minor. Throw, hit and bell cues use a separate sound channel. Stone joints, roof chips, leaf clusters, tablecloth edges, plates, windows and bunting distinguish the spaces. The title and photo scenes are quiet.</p>
<h2>What passed</h2><p>The exact downloadable ROM and exact browser-export ROM both completed the full game in the emulator and recovered all three saved unlocks after the engine's native soft restart. Separate runs covered both grove routes, optional high wool, the lower-route head-bump fix, and zero-inventory entry into the final grove and banquet courts. Contact damage and knockback passed in the recorded gameplay build and again in the current release. Start restored three hearts and cleared carried wool. The final art pass keeps his embroidered face fixed. Three living patrols each moved 7.5 pixels over ten native frames. Sampled bell and table scenes in the current release peaked at nine sprites per scanline against the hardware limit of ten.</p>
<p>The native project reports zero validation errors. The cartridge header, checksum and color mode are valid. Both export ROMs boot to the unobstructed cover. The official browser export contains the latest playable build. The disconnected prior preview and its export remain for state recovery. Both exact final exports were played through again after the bell, table and HUD update. The unchanged title resources previously passed these checks: holding A only opens the selector; it does not also select a stage. A and Start opening, B closing, locked-stage messaging and selection of a saved unlocked stage passed.</p>
<div class="note">Your Chromatic pass is next. Try the upper and lower grove paths, the wide stone-island jump, the banquet's last landing, and the music volume on the speaker. Cartridge power-cycle persistence and hardware sound balance remain for that pass. Browser save persistence across closing the browser was not tested.</div>
<p class="small">Native SHA-256: <code>{native}</code><br>Browser ROM SHA-256: <code>{web}</code></p>'''
(DESIGN/'version-1.html').write_text(doc('Kittie version 1',body))
roadmap='''<h1>Version 1 is complete</h1><p class="lead">Three stages, 28 screens, a stage menu with saved unlocks, original music, textures, character reactions and a wedding ending.</p><p><a href="version-1.html">Play guide and recorded gameplay</a> · <a href="../courtyard/build/kittie-complete-v1.gbc">Download ROM</a></p><table><tr><th>Milestone</th><th>Status</th></tr><tr><td>Collect, carry, throw, retrieve</td><td>Implemented. Three-ball capacity; only bells and goons use wool. No automatic return.</td></tr><tr><td>Recognizable Kittie</td><td>Revised oval face, separated eyes and smile, approved low body and short legs. Back carry, idle cuddle, a pleased body bob and tucked-paw recoil.</td></tr><tr><td>Distinct olive grove</td><td>11 screens. Raised islands, wider gaps, optional high wool, lower patrol lane and one exit bell.</td></tr><tr><td>Banquet finale</td><td>9 screens. Table crossings, chair steps, low shots and the wedding photo. Connected after the 8-screen courtyard.</td></tr><tr><td>Saved stage unlocks</td><td>Native save/peek events. Full unlock recovery passed an engine soft restart that clears game variables.</td></tr><tr><td>Presentation pass</td><td>Original stage melodies and bass, environment texture, approved portrait cover, stage selector overlay and wedding ending.</td></tr></table><h2>Next, use the hardware feedback</h2><p>The user will handle the Chromatic test. Use that playthrough to tune any unfair landing, confusing recovery, sprite readability or speaker balance. Do not add a fourth level or more ball powers before that feedback. Richer art and longer musical arrangements can follow if the core play earns them.</p><p>Native emulator play reached the ending in both exact final exports. Physical power-cycle saves, hardware frame pacing and sound balance remain unverified.</p>'''
(DESIGN/'expansion-roadmap.html').write_text(doc('Kittie development status',roadmap))
(GAME/'README.html').write_text(doc('Kittie version 1','''<h1>Kittie Has Other Plans Version 1</h1><p>Three connected Game Boy Color stages for ModRetro Chromatic: 8-screen courtyard, 11-screen olive grove and 9-screen wedding banquet.</p><p><a href="build/kittie-complete-v1.gbc">Download the ROM</a> · <a href="../design/version-1.html">Controls, maps and verification</a> · <a href="project.gbsproj">Editable GB Studio project</a></p><img src="artifacts/version-1-title.png" width="320" height="288" alt="Final native portrait cover"><p>Arrows / D-pad move. Z / A jumps. X / B throws. Up + throw lobs. Enter / Start retries. P / Select returns to the cover. A or Start opens the title selector; B closes it. A confirms a stage or dialogue. Cleared stages unlock the next one and save progress.</p><p>Both exact release ROMs completed the full game in the emulator. The user will test physical Chromatic behavior.</p>'''))
print('Updated version guide, roadmap, three stage maps and README.html')
