"""Generate the user-facing HTML guide and maps from authoritative stage JSON."""
from pathlib import Path
import json, html
ROOT=Path(__file__).resolve().parents[2]
GAME=ROOT/'courtyard'; DESIGN=ROOT/'design'
style='''body{margin:0;background:#f5edd8;color:#403b3d;font:16px/1.65 system-ui,sans-serif}main{max-width:1060px;margin:auto;padding:40px 24px 64px}h1{font-size:42px;line-height:1.12;max-width:800px}h2{font-size:24px;line-height:1.25;margin-top:32px}h3{font-size:18px}a{color:#704373}p{max-width:800px}.lead{font-size:21px}.note{padding:18px 22px;background:#e5e8d2;border-left:4px solid #66834f}img{max-width:100%;height:auto;image-rendering:pixelated}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{padding:18px;background:#faf5e9;border:1px solid #cbb78f}.card p{font-size:15px}.map{overflow:auto;border:1px solid #cbb78f;background:#faf5e9}table{border-collapse:collapse;width:100%;font-size:15px}th,td{text-align:left;vertical-align:top;border-bottom:1px solid #cbb78f;padding:12px 8px}code{font-size:12px;overflow-wrap:anywhere}.small{font-size:13px;color:#675e57}@media(max-width:700px){.cards{grid-template-columns:1fr}h1{font-size:32px}}'''
def doc(title,body):return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>{style}</style></head><body><main>{body}</main></body></html>'
def diagram(level):
 w=level['width'];parts=[f'<svg width="{w}" height="176" viewBox="0 0 {w} 176" role="img" aria-label="Stage geometry, balls, bells and patrols"><rect width="{w}" height="176" fill="#faf5e9"/><rect y="128" width="{w}" height="16" fill="#66834f"/>']
 for x in range(0,w,160):parts.append(f'<path d="M{x},20V144" stroke="#cbb78f" stroke-dasharray="4 4"/><text x="{x+8}" y="15" font-size="12">{x//160+1}</text>')
 for x,r,_ in level['gaps']:parts.append(f'<rect x="{x}" y="128" width="{r-x}" height="16" fill="#83c7dc"/>')
 for i,(x,y,r,b) in enumerate(level['solids']):
  if i in level['gate_indices'] and level.get('initial_gate',0)&(1<<level['gate_indices'].index(i)):continue
  color='#9773b3' if i in level['gate_indices'] else '#a18969'
  opacity='.4' if i==level['door_index'] else '1'
  parts.append(f'<rect x="{x}" y="{max(y,20)}" width="{r-x}" height="{b-max(y,20)}" fill="{color}" opacity="{opacity}"/>')
 for i,(lo,hi) in enumerate(level['goons']):
  y=level.get('goon_heights',[128]*3)[i]-8
  parts.append(f'<path d="M{lo},{y}H{hi}" stroke="#704373"/><circle cx="{(lo+hi)/2}" cy="{y}" r="6" fill="#704373"/>')
 for x,y in level['balls']:parts.append(f'<circle cx="{x}" cy="{y}" r="5" fill="#d87098" stroke="#733b65"/>')
 for i,c in enumerate(level['courts']):
  if level.get('initial_gate',0)&(1<<i):continue
  x,y=c['bell_x'],c['bell_y'];parts.append(f'<path d="M{x-5},{y+4}h10l-2,-9h-6z" fill="#d7a343"/>')
 parts.append('</svg>');return ''.join(parts)
manifest=json.loads((ROOT/'release/manifest.json').read_text())
version=manifest['version']; download=manifest['downloadUrl']
levels=[json.loads((GAME/f'tools/{n}.json').read_text()) for n in ('level','grove','banquet')]
names=['The courtyard','The olive grove','The wedding banquet']
files=['level-plan.html','olive-grove.html','banquet.html']
intros=[
 'Eight screens introduce collection, ball recovery, gaps and bell gates. A route fork and a low table shot lead to the exit.',
 'Eleven screens of irrigation terraces, three short high ledges and a lower patrol route. A 64-pixel late channel leads to an open bell garden.',
 'Nine screens cross the wedding tables and chairs. A tabletop patrol and elevated final bell lead to the wedding photograph.'
]
for name,file,intro,level in zip(names,files,intros,levels):
 body=f'''<p class="small">Release {version}</p><h1>{name}</h1><p class="lead">{intro}</p><p><a href="version-1.html">Play guide</a></p><div class="map">{diagram(level)}</div><p>Scroll to see the whole stage. Pink circles are the three physical wool balls; blue channels reset the stage; purple bars mark closed bell gates. Patrol lines show each goon's constant-speed range. This is a geometry diagram, not a screenshot.</p><p>Collect, throw and retrieve balls. Water permanently removes a ball until the stage is retried. Start retries; Select returns to the cover. The grove and banquet final gardens remain open for backtracking.</p>'''
 (DESIGN/file).write_text(doc(name,body))
cards=''.join(f'<article class="card"><h3>{name}</h3><p>{intro}</p><a href="{file}">Level map</a></article>' for name,intro,file in zip(names,intros,files))
body=f'''<p class="small">Release {version} · {manifest['date']} · Game Boy Color / ModRetro Chromatic</p><h1>Kittie Has Other Plans</h1><p class="lead">A plush cat, three wool balls per stage, and a Tuscan wedding. Three connected stages span 28 screens.</p><p><a href="{download}">Download the release ROM</a> · <a href="https://github.com/jintaili/kittie-game/releases/tag/v{version}">Release and checksum</a> · <a href="../courtyard/project.gbsproj">Editable project</a></p><img src="media/cover.png" width="320" height="288" alt="Native release cover"><div class="cards">{cards}</div>
<h2>Controls</h2><table><tr><th>Action</th><th>Chromatic</th><th>Browser</th></tr><tr><td>Move and collect balls</td><td>D-pad; touch a ball</td><td>Arrow keys</td></tr><tr><td>Jump; hold for height</td><td>A</td><td>Z</td></tr><tr><td>Throw / high lob</td><td>B / Up+B</td><td>X / Up+X</td></tr><tr><td>Retry the current stage</td><td>Start</td><td>Enter</td></tr><tr><td>Return to cover</td><td>Select</td><td>P</td></tr><tr><td>Open / close stage selector</td><td>A or Start / B</td><td>Z or Enter / X</td></tr><tr><td>Confirm / continue</td><td>A</td><td>Z</td></tr></table>
<h2>Balls, health and progress</h2><p>Each stage has three physical balls and starts Kittie with three hearts. He can carry up to three balls. Balls defeat goons and ring bells; they never return automatically or boost jumps. Retrieve them where they land. Balls lost in water stay lost until retry; losing useful balls may require restarting the stage.</p><p>Goon contact costs a heart and causes knockback with brief protection. Gaps and zero hearts reset the whole stage. Goons patrol at constant speed. There are no checkpoints. Clearing a stage saves the next unlock to cartridge RAM. Replaying an earlier stage never removes later unlocks; mid-stage positions are not saved.</p>
<h2>Kittie and the wedding</h2><p>Kittie is male. His low oval face, embroidered eyes and grin, short legs and low body follow the original plush photographs. Reactions use his body and paws while his face stays fixed. A pink wool ball rides on his back; the taupe shape beneath his face is his paw. He cuddles a ball while idle. The cover remains visible until A or Start opens the selector; B closes it.</p><img src="media/grove.png" width="320" height="288" alt="Native reviewed grove"><img src="media/banquet.png" width="320" height="288" alt="Native reviewed wedding arch"><p>Each stage has its own original melody and bass accompaniment. Throw, hit and bell sounds accompany play. The cover and wedding photo are quiet. These stage screenshots come from the final level reviews; their artwork is unchanged in this release.</p>
<h2>Release verification</h2><p>The exact downloadable cartridge completed the courtyard, revised grove and revised banquet, returned to the cover, and recovered unlock value 3 after a native soft restart. Independent reviewers approved all three levels. The final combined run includes a grove retry; preserved inputs record that failure and the successful continuation.</p><p>The user reported a successful Chromatic playtest on {manifest['date']}. Individual hardware checks and the tested cartridge hash were not separately enumerated. Browser persistence after closing the browser was not tested.</p><p><a href="../release/manifest.json">Release identity</a> · <a href="../release/verification.json">Exact emulator inputs and evidence</a> · <a href="expansion-roadmap.html">Roadmap status</a></p><p class="small">SHA-256: <code>{manifest['sha256']}</code></p>'''
(DESIGN/'version-1.html').write_text(doc('Kittie Has Other Plans · '+version,body))
road=f'''<h1>The expansion roadmap is complete</h1><p class="lead">Release {version} has 28 screens, three connected stages, saved stage unlocks, music, textures, character reactions and the wedding ending.</p><p>The courtyard, grove and banquet have each passed the whole-level agent review. The user reported a successful Chromatic test on {manifest['date']}. Release cleanup is complete, and the latest combined cartridge passed a full-game emulator run and soft-restart unlock check.</p><p><a href="version-1.html">Current play guide</a> · <a href="{download}">Release cartridge</a></p><h2>Optional future work</h2><p>Longer music arrangements and screen-fixed courtyard hints remain optional polish. New levels or ball powers are future scope, not unfinished requirements for this release. The browser annotation-exit issue belongs to the preview plugin and is separate from the cartridge.</p>'''
(DESIGN/'expansion-roadmap.html').write_text(doc('Kittie development status',road))
(GAME/'README.html').write_text(doc('Kittie Has Other Plans',f'<h1>Kittie Has Other Plans</h1><p>Release {version}, 28 screens for Game Boy Color and ModRetro Chromatic.</p><p><a href="../design/version-1.html">Play guide, maps and controls</a> · <a href="{download}">Download ROM</a> · <a href="project.gbsproj">Editable GB Studio project</a></p>'))
print('Updated release guide, stage maps, roadmap and project landing page.')
